### ISSUE TITLE
Document suggested arguments to `hash` for beginners

### ISSUE THREAD

**Issue by seagreen** [centromere/blake2#1]
My impression is that the most standard way to call `Crypto.Hash.BLAKE2.BLAKE2b.hash` is `hash 64 mempty`, but I had to look in the benchmarks to make sure. It would be nice to have more info about this in the Haddocks. I'd be happy to look through the spec and make a PR if you'd like one.

**Comment by centromere** [comment]
@seagreen: Is [this](https://github.com/centromere/blake2/blob/e3f011a834b283d3ab96d55f311b0926618808c2/src/Crypto/Hash/BLAKE2/BLAKE2b.hsc#L75) what you intended?

**Comment by seagreen** [comment]
Exactly, looks great!
