### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by chris-martin** [centromere/blake2#11]
I'd be happy to come on as a maintainer to help get this package up to date with the latest dependencies, fix the version bounds of older releases, update the package metadata, get the CI working again, etc.

**Comment by centromere** [comment]
Thank you for your contributions. If you could get CI working again, I'd be much obliged! Do you need anything from me?

**Comment by chris-martin** [comment]
Would you mind giving me commit privileges on the github repository and adding `chris_martin` as a [maintainer](https://hackage.haskell.org/package/blake2/maintainers/) on Hackage? Otherwise I guess I can give you a boring checklist of requests for metadata revisions and github settings to tweak.

I'd love it if we could enable the "Discussions" github tab, as I have a few things to talk about that aren't really "issues" but rather ongoing chats, e.g. users' and maintainers' priorities regarding which GHC versions to support.

**Comment by centromere** [comment]
I do not think I have permission to give you commit privileges.

@Kleidukos, are you able to assist?

**Comment by centromere** [comment]
I've added you as a maintainer on Hackage.

**Comment by Kleidukos** [comment]
@centromere good catch, you should be full admin now.
@chris-martin I've added you :)

**Comment by chris-martin** [comment]
Revised existing releases to add appropriate `base16-bytestring` upper bound. Should get a release out soon!
