### ISSUE TITLE
i686 support?

### ISSUE THREAD

**Issue by peti** [centromere/blake2#2]
Is there any way to build this package on 32 bit platforms? My attempts at doing so were unsuccessful:

```
[   45s] include/blake2-config.h:68:2:
[   45s]      error: #error "This code requires at least SSE2."
[   45s]      #error "This code requires at least SSE2."
```

**Comment by centromere** [comment]
What is the exact CPU you are using?

**Comment by peti** [comment]
I don't know. The build farm schedules these build on any of ~700 workers who run the build in a virtual machine then.

**Comment by centromere** [comment]
@peti: I've just added i686 support. Please try building the master branch on your build farm and let me know if it works.

**Comment by peti** [comment]
I tried it, and the current `master` branch compiles fine on i586!

**Comment by centromere** [comment]
Wonderful. Thank you for testing!
