### ISSUE TITLE
Document the difference between this and cryptonite

### ISSUE THREAD

**Issue by seagreen** [centromere/blake2#3]
Is the purpose of this library to provide blake2 hashing with fewer dependencies than cryptonite, or does it have some other emphasis? I think a fair amount of users (in addition to me) will have this question, so it might make sense to put the answer in the README.

**Comment by centromere** [comment]
Thank you for the suggestion. I've modified the README in the master repo accordingly.

**Comment by seagreen** [comment]
Looks perfect. Thanks for considering my doc suggestions, hopefully they help other people too=)
