### ISSUE TITLE
C code is out-of-date and contains horrible bugs

### ISSUE THREAD

**Issue by infinity0** [centromere/blake2#5]
In particular, we experienced something very similar to https://github.com/BLAKE2/BLAKE2/pull/36 however unfortunately we don't have a specific test case for you as we only saw it in not-yet-released non-public code and did not figure out how to reproduce it in a unit test.

**Comment by infinity0** [comment]
OTOH the `cryptonite` package worked fine for us and the code there is much more up-to-date wrt BLAKE2/BLAKE2 as well

**Comment by centromere** [comment]
I don't have time to get to this yet but I appreciate you putting it on my radar.
