### ISSUE TITLE
Since June 15th, 2021, the building on travis-ci.org is ceased

### ISSUE THREAD

**Issue by Kleidukos** [centromere/blake2#7]
It was not noticed because the latest commit (to this day) is from the 3rd of April, but we should probably move the CI setup to GitHub Actions

**Comment by chris-martin** [comment]
I guess I don't know what I'm doing with github actions anymore. I had given up on it because I don't know how to get it to cache `/nix/store` and github cache restore times are crap anyway. I don't suppose the haskell foundation or somebody has a paid cachix account we could use?

**Comment by Kleidukos** [comment]
@chris-martin Are you beholden to nix? From a cursory glance at flake.nix it doesn't seem like there is a dire need for the features nix brings.

**Comment by chris-martin** [comment]
No, just disappointed.

**Comment by chris-martin** [comment]
CI is up!
